### ISSUE TITLE
Use of unresolved operator '>>>-'  complie in swift 3  error

### ISSUE THREAD

**Issue by izenloading** [Ramotion/preview-transition#13]
[NSLayoutAttribute.left, .right, .bottom, .top].forEach { attribute in
      (self.controlView, screnShotImageView) >>>- {
        $0.attribute = attribute
        return
      }

Use of unresolved operator '>>>-'

please help me 
thanks

**Comment by JesseRubio** [comment]
I came across the same issue so what I did was drag and drop the ConstraintsHalper.swift file into the project. The pod file has the ContraintsHalper.swift file embedded in it but for some reason, xcode doesn't read it. Hope this helps.
