### ISSUE TITLE
Image Content Mode

### ISSUE THREAD

**Issue by ElyDantas** [Ramotion/preview-transition#15]
How to set image content mode after loading image into ImageView ?

Tried many ways, no success:

`cell.imageView?.contentMode = .scaleAspectFit`
`cell.bgImage?.contentMode = .scaleAspectFit`
`cell.backgroundView?.contentMode = .scaleAspectFit`

**Comment by ikolpachkov** [comment]
Now `cell.bgImage?.contentMode = .scaleAspectFit` works fine
