### ISSUE TITLE
How i can run it on Xcode 7.2? 

### ISSUE THREAD

**Issue by zafar007** [Ramotion/preview-transition#6]
Ive tried to run it on Xcode 7.2 but getting this error.

> Type of expression is ambiguous without more context

. Can anyone please tell me how i can resolve it or anyone please send me that project for 7.2. Thanks 

[Error](https://drive.google.com/open?id=0B29ka7gbDAYxS0p1Z0g1QlVOR3M)

**Comment by Juriv** [comment]
we don't support xcode 7.2 anymore

**Comment by zafar007** [comment]
.k thanks
